const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{URL}=require('node:url');
const PORT=Number(process.env.PORT||10000),ROOT=process.env.STORAGE_ROOT||path.join(process.cwd(),'storage'),DATA=path.join(ROOT,'data.json'),SESS=path.join(ROOT,'sessions.json');
fs.mkdirSync(ROOT,{recursive:true});
const secret=process.env.SESSION_SECRET||'development-only-secret-change-me-please-32';
const bootstrapEmail=(process.env.BOOTSTRAP_ADMIN_EMAIL||'miguelalvesmillk@gmail.com').trim().toLowerCase(),bootstrapPassword=process.env.BOOTSTRAP_ADMIN_PASSWORD||'change-this-before-production';
const empty={users:[],sources:[],channels:[],movies:[],series:[],episodes:[],verificationRuns:[],generatedSources:[],studioProjects:[]};
function read(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return fallback}}
function write(file,obj){const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(obj,null,2));fs.renameSync(tmp,file)}
let db=read(DATA,empty); let sessions=read(SESS,{});
function hash(p){const salt=crypto.randomBytes(16).toString('hex');const h=crypto.pbkdf2Sync(p,salt,210000,32,'sha256').toString('hex');return `pbkdf2$210000$${salt}$${h}`}
function verify(p,e){const [s,i,salt,h]=String(e).split('$');if(s!=='pbkdf2'||i!=='210000')return false;const a=crypto.pbkdf2Sync(p,salt,210000,32,'sha256').toString('hex');return a.length===h.length&&crypto.timingSafeEqual(Buffer.from(a),Buffer.from(h))}
if(!db.users.length){db.users.push({id:crypto.randomUUID(),email:bootstrapEmail,passwordHash:hash(bootstrapPassword),createdAt:new Date().toISOString()});write(DATA,db)}
function send(res,status,type,body,headers={}){res.writeHead(status,{'content-type':type,'cache-control':'no-store',...headers});res.end(body)}
function json(res,status,obj,headers={}){send(res,status,'application/json; charset=utf-8',JSON.stringify(obj),headers)}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>2e6)throw Error('Payload muito grande')}return s?JSON.parse(s):{}}
function cookieToken(req){const m=(req.headers.cookie||'').match(/(?:^|;\s*)los_session=([^;]+)/);return m?.[1]||null}
function user(req){const t=cookieToken(req),v=t&&sessions[t];if(!v||v.expires<Date.now()){if(t){delete sessions[t];write(SESS,sessions)}return null}return db.users.find(x=>x.id===v.userId)||null}
function auth(req,res){const u=user(req);if(!u){json(res,401,{error:'UNAUTHORIZED'});return null}return u}
function safeUrl(raw){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw Error('Somente HTTP/HTTPS');const h=u.hostname.toLowerCase();if(h==='localhost'||h.endsWith('.local')||/^127\.|^10\.|^192\.168\.|^169\.254\./.test(h)||h==='0.0.0.0')throw Error('Destino privado bloqueado');return u}
function attrs(s){const o={};for(const m of s.matchAll(/([\w-]+)="([^"]*)"/g))o[m[1]]=m[2];return o}
function extractWebsiteItems(text){const out=[];const seen=new Set();const re=/https?:\/\/[^\s"'<>]+/gi;for(const m of text.matchAll(re)){const raw=m[0].replace(/[),.;]+$/g,'');if(seen.has(raw))continue;if(!/\.(m3u8?|mp4|mkv|ts|mpd)(?:$|[?#])/i.test(raw)&&!/(stream|live|playlist|video|movie|episode)/i.test(raw))continue;seen.add(raw);const lower=raw.toLowerCase();let type='channel';if(/movie|filme/.test(lower))type='movie';else if(/episode|episodio/.test(lower))type='episode';let clean='Stream detectado';try{clean=decodeURIComponent(raw.split('/').pop().split('?')[0]||'stream').replace(/[-_]+/g,' ').replace(/\.[a-z0-9]+$/i,'').trim()||clean}catch{}out.push({id:crypto.randomUUID(),type,name:clean,originalName:clean,group:'',logo:'',streamUrl:raw,status:'unknown',metadata:{discoveredFrom:'website'}})}return out}
function parseM3U(text){const lines=text.split(/\r?\n/).map(x=>x.trim()),out=[];for(let i=0;i<lines.length;i++){if(!lines[i].startsWith('#EXTINF'))continue;const a=attrs(lines[i]),name=lines[i].split(',').slice(1).join(',').trim()||a['tvg-name']||'Sem nome',url=lines[i+1]&&!lines[i+1].startsWith('#')?lines[i+1]:'';if(!url)continue;out.push({id:crypto.randomUUID(),type:a.type==='movie'?'movie':a.type==='episode'?'episode':'channel',name,originalName:name,group:a['group-title']||'',logo:a['tvg-logo']||'',streamUrl:url,status:'unknown',metadata:{}})}return out}
function makeM3U(items){return ['#EXTM3U',...items.map(x=>`#EXTINF:-1 tvg-name="${String(x.name||'').replaceAll('"','&quot;')}"${x.group?` group-title="${String(x.group).replaceAll('"','&quot;')}"`:''}${x.logo?` tvg-logo="${String(x.logo).replaceAll('"','&quot;')}"`:''},${x.name||'Sem nome'}\n${x.streamUrl||''}`)].join('\n')}
async function collect(raw){const u=safeUrl(raw),ac=new AbortController(),timer=setTimeout(()=>ac.abort(),15000);try{const r=await fetch(u,{redirect:'follow',signal:ac.signal,headers:{'user-agent':'LOS-COLLECTOR/3.0'}});if(!r.ok)throw Error(`HTTP ${r.status}`);const text=await r.text();if(text.length>8e6)throw Error('Resposta muito grande');const ct=r.headers.get('content-type')||'';if(u.pathname.match(/\.(m3u8?|txt)$/i)||ct.includes('mpegurl')||text.startsWith('#EXTM3U'))return {kind:'m3u',items:parseM3U(text)};return {kind:'website',items:extractWebsiteItems(text),title:text.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]+>/g,'').trim()||''}}finally{clearTimeout(timer)}}
async function check(raw){const start=Date.now();try{const u=safeUrl(raw),ac=new AbortController(),timer=setTimeout(()=>ac.abort(),10000);let r;try{r=await fetch(u,{method:'HEAD',redirect:'follow',signal:ac.signal,headers:{'user-agent':'LOS-COLLECTOR-CHECK/3.0'}});if(r.status===405||r.status===501)r=await fetch(u,{method:'GET',redirect:'follow',signal:ac.signal,headers:{range:'bytes=0-0','user-agent':'LOS-COLLECTOR-CHECK/3.0'}})}finally{clearTimeout(timer)}return {status:r.ok?'online':'error',httpStatus:r.status,responseMs:Date.now()-start,reason:r.ok?'OK':`HTTP ${r.status}`}}catch(e){return {status:e.name==='AbortError'?'timeout':'error',responseMs:Date.now()-start,reason:e.name==='AbortError'?'Timeout':e.message}}}
function dashboardHtml(){return fs.readFileSync(path.join(__dirname,'public','app.html'),'utf8')}
async function api(req,res,url){const p=url.pathname;if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,time:new Date().toISOString()});if(req.method==='POST'&&p==='/api/auth/login'){try{const b=await body(req),e=String(b.email||'').trim().toLowerCase(),pw=String(b.password||''),u=db.users.find(x=>x.email===e);if(!u||!verify(pw,u.passwordHash))return json(res,401,{error:'Email ou senha inválidos'});const t=crypto.randomBytes(32).toString('base64url');sessions[t]={userId:u.id,expires:Date.now()+2592e6};write(SESS,sessions);return json(res,200,{ok:true},{'set-cookie':`los_session=${t}; HttpOnly; Path=/; SameSite=Lax; ${process.env.NODE_ENV==='production'?'Secure; ':''}Max-Age=2592000`})}catch(e){return json(res,400,{error:e.message})}}
if(req.method==='POST'&&p==='/api/auth/logout'){const t=cookieToken(req);if(t){delete sessions[t];write(SESS,sessions)}return json(res,200,{ok:true},{'set-cookie':'los_session=; HttpOnly; Path=/; Max-Age=0; SameSite=Lax'})}
const u=auth(req,res);if(!u)return;
if(req.method==='GET'&&p==='/api/auth/me')return json(res,200,{user:{id:u.id,email:u.email}});
if(req.method==='POST'&&p==='/api/auth/change-password'){try{const b=await body(req),old=String(b.currentPassword||''),nw=String(b.newPassword||'');if(nw.length<10)return json(res,400,{error:'A nova senha deve ter pelo menos 10 caracteres'});if(!verify(old,u.passwordHash))return json(res,400,{error:'Senha atual inválida'});u.passwordHash=hash(nw);write(DATA,db);sessions={};write(SESS,sessions);return json(res,200,{ok:true})}catch(e){return json(res,400,{error:e.message})}}
if(req.method==='GET'&&p==='/api/sources')return json(res,200,{items:db.sources.map(s=>({...s,counts:{channels:db.channels.filter(x=>x.sourceId===s.id).length,movies:db.movies.filter(x=>x.sourceId===s.id).length,series:db.series.filter(x=>x.sourceId===s.id).length,episodes:db.episodes.filter(x=>x.sourceId===s.id).length}}))});
if(req.method==='POST'&&p==='/api/sources'){try{const b=await body(req),name=String(b.name||'').trim(),raw=String(b.url||'').trim(),type=String(b.type||'website');if(!name||!raw)throw Error('Nome e URL são obrigatórios');safeUrl(raw);const s={id:crypto.randomUUID(),name,url:raw,type,status:'active',createdAt:new Date().toISOString(),lastCollectedAt:null,lastVerifiedAt:null};db.sources.unshift(s);write(DATA,db);let collected=null;if(b.collectNow){collected=await collect(raw);if(collected.items?.length){for(const x of collected.items){x.sourceId=s.id;if(x.type==='movie')db.movies.push({...x,title:x.name,sourceId:s.id});else if(x.type==='episode')db.episodes.push({...x,sourceId:s.id,season:1,episode:1,title:x.name,seriesId:null});else db.channels.push({...x,sourceId:s.id})}s.lastCollectedAt=new Date().toISOString();write(DATA,db)}}return json(res,201,{source:s,collected})}catch(e){return json(res,400,{error:e.message})}}
if(req.method==='DELETE'&&p.startsWith('/api/sources/')){const id=p.split('/').pop();const idx=db.sources.findIndex(x=>x.id===id);if(idx<0)return json(res,404,{error:'Fonte não encontrada'});db.sources.splice(idx,1);for(const key of ['channels','movies','series','episodes'])db[key]=db[key].filter(x=>x.sourceId!==id);write(DATA,db);return json(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/collect'){try{const b=await body(req);return json(res,200,await collect(String(b.url||'')))}catch(e){return json(res,400,{error:e.message})}}
if(req.method==='GET'&&p==='/api/library'){const q=String(url.searchParams.get('search')||'').toLowerCase(),match=x=>String(x.name||x.title||'').toLowerCase().includes(q);return json(res,200,{channels:db.channels.filter(match).slice(0,500),movies:db.movies.filter(match).slice(0,500),series:db.series.filter(match).slice(0,500),episodes:db.episodes.filter(match).slice(0,500)})}
if(req.method==='POST'&&p==='/api/diagnosis'){const all=[...db.channels.map(x=>['channel',x]),...db.movies.map(x=>['movie',x]),...db.episodes.map(x=>['episode',x])].slice(0,100);let online=0,errors=0,timeouts=0;const results=[];for(const [type,x] of all){const r=await check(x.streamUrl);if(r.status==='online')online++;else if(r.status==='timeout')timeouts++;else errors++;x.status=r.status;x.lastVerifiedAt=new Date().toISOString();results.push({type,id:x.id,...r})}db.verificationRuns.unshift({id:crypto.randomUUID(),total:all.length,online,errors,timeouts,results,finishedAt:new Date().toISOString()});write(DATA,db);return json(res,200,{total:all.length,online,errors,timeouts,results})}
if(req.method==='POST'&&p==='/api/monitoring/run'){let online=0,errors=0;const started=new Date().toISOString();const items=[...db.channels,...db.movies,...db.episodes].slice(0,100);for(const x of items){const r=await check(x.streamUrl);x.status=r.status;x.lastVerifiedAt=new Date().toISOString();if(r.status==='online')online++;else errors++}db.verificationRuns.unshift({id:crypto.randomUUID(),total:items.length,online,errors,timeouts:items.length-online-errors,finishedAt:new Date().toISOString(),startedAt:started});write(DATA,db);return json(res,200,{total:items.length,online,errors})}
if(req.method==='GET'&&p==='/api/generated')return json(res,200,{items:db.generatedSources});
if(req.method==='GET'&&p.startsWith('/api/generated/')){const id=p.split('/').pop(),g=db.generatedSources.find(x=>x.id===id);if(!g)return json(res,404,{error:'Fonte não encontrada'});return send(res,200,'application/vnd.apple.mpegurl; charset=utf-8',g.content,{'content-disposition':`attachment; filename="${g.name.replace(/[^a-z0-9_-]+/gi,'_')}.m3u"`})}
if(req.method==='POST'&&p==='/api/generated'){try{const b=await body(req),items=Array.isArray(b.items)?b.items:[],g={id:crypto.randomUUID(),name:String(b.name||'Fonte LOS'),format:'m3u',itemCount:items.length,content:makeM3U(items),createdAt:new Date().toISOString()};db.generatedSources.unshift(g);write(DATA,db);return json(res,201,g)}catch(e){return json(res,400,{error:e.message})}}
if(req.method==='POST'&&p==='/api/merge'){const b=await body(req),ids=new Set(Array.isArray(b.sourceIds)?b.sourceIds:[]),all=[...db.channels,...db.movies,...db.episodes].filter(x=>ids.has(x.sourceId)),seen=new Set(),items=[];for(const x of all){const k=String(x.streamUrl||x.name).trim().toLowerCase();if(!k||seen.has(k))continue;seen.add(k);items.push({name:x.name||x.title,streamUrl:x.streamUrl,group:x.group||x.groupName,logo:x.logo,type:x.type||'channel'})}return json(res,200,{count:items.length,items,preview:makeM3U(items)})}
if(req.method==='POST'&&p.match(/^\/api\/studio\/[^/]+\/render$/)){const id=p.split('/')[3],x=db.studioProjects.find(v=>v.id===id);if(!x)return json(res,404,{error:'Projeto não encontrado'});if(!x.backgroundUrl)return json(res,400,{error:'Informe uma URL de vídeo autorizada'});try{safeUrl(x.backgroundUrl);const {spawn}=require('node:child_process'),out=path.join(ROOT,`studio-${id}.mp4`);x.status='rendering';write(DATA,db);await new Promise((resolve,reject)=>{const args=['-y','-i',x.backgroundUrl,'-t',String(x.duration),'-vf',x.format==='16:9'?'scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2':'scale=720:1280:force_original_aspect_ratio=decrease,pad=720:1280:(ow-iw)/2:(oh-ih)/2','-c:v','libx264','-preset','veryfast','-c:a','aac','-movflags','+faststart',out];const f=spawn('ffmpeg',args,{stdio:['ignore','ignore','pipe']});let err='';f.stderr.on('data',d=>err+=d);f.on('error',reject);f.on('close',code=>code===0?resolve():reject(Error(err.slice(-500)||`ffmpeg exited ${code}`))) });x.status='rendered';x.outputPath=out;write(DATA,db);return json(res,200,{ok:true,path:out})}catch(e){x.status='error';write(DATA,db);return json(res,500,{error:e.message})}}
if(req.method==='GET'&&p==='/api/studio')return json(res,200,{items:db.studioProjects});
if(req.method==='POST'&&p==='/api/studio'){const b=await body(req),x={id:crypto.randomUUID(),title:String(b.title||'Projeto sem título'),description:String(b.description||''),coverUrl:String(b.coverUrl||''),backgroundUrl:String(b.backgroundUrl||''),format:b.format==='16:9'?'16:9':'9:16',duration:Math.min(60,Math.max(5,Number(b.duration)||15)),status:'draft',createdAt:new Date().toISOString()};db.studioProjects.unshift(x);write(DATA,db);return json(res,201,x)}
return json(res,404,{error:'Not found'})}
if(process.argv.includes('--monitor')){(async()=>{const items=[...db.channels,...db.movies,...db.episodes].slice(0,100);let online=0,errors=0;for(const x of items){const r=await check(x.streamUrl);x.status=r.status;x.lastVerifiedAt=new Date().toISOString();r.status==='online'?online++:errors++}write(DATA,db);console.log(JSON.stringify({total:items.length,online,errors}));process.exit(0)})()}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(req.method==='GET'){if(url.pathname==='/'||url.pathname==='/login'||url.pathname==='/dashboard'||url.pathname.startsWith('/sources')||url.pathname.startsWith('/library')||url.pathname.startsWith('/diagnosis')||url.pathname.startsWith('/monitoring')||url.pathname.startsWith('/merge')||url.pathname.startsWith('/generated')||url.pathname.startsWith('/studio')||url.pathname.startsWith('/settings'))return send(res,200,'text/html; charset=utf-8',dashboardHtml());const file=path.join(__dirname,'public',url.pathname.slice(1));if(file.startsWith(path.join(__dirname,'public'))&&fs.existsSync(file))return send(res,200,`text/${path.extname(file)==='.css'?'css':'javascript'}`,fs.readFileSync(file))}send(res,404,'text/plain','Not found')}catch(e){console.error(e);json(res,500,{error:'Internal server error'})}});server.listen(PORT,'0.0.0.0',()=>console.log(`LOS COLLECTOR listening on ${PORT}`));